# Configuration documentation:
# https://docs.getnao.io/nao-agent/context-builder/configuration#nao_config-yaml

project_name: nao-playground

databases:
  - name: postgres
    type: postgres
    host: "{{ env('DATA_SOURCE_HOST') }}"
    port: 5432
    database: "{{ env('DATA_SOURCE_DB_NAME') }}"
    user: "{{ env('DATA_SOURCE_USER') }}"
    password: "{{ env('DATA_SOURCE_PASSWORD') }}"
    schema_name: public
    accessors: [columns, preview, description]
    include: []
    exclude: []

repos: []

llm:
  provider: openai
  api_key: "{{ env('OPENAI_API_KEY') }}"

notion:
  api_key: ""
  pages: []

slack: null
